from typing import Protocol, runtime_checkable

from app.domain.models import RetrievedChunk


class VectorStore(Protocol):
    async def ensure_collection(self, vector_size: int) -> None: ...
    async def upsert(self, chunks: list[dict]) -> None: ...
    async def search(self, query_vector: list[float], limit: int = 5, workspace_id: str | None = None) -> list[RetrievedChunk]: ...
    async def health_check(self) -> bool: ...
    async def get_document_hash(self, doc_id: str, workspace_id: str) -> str | None: ...
    async def replace_document(self, document: dict, chunks: list[dict]) -> None: ...
    async def delete_missing_documents(self, root_path: str, workspace_id: str, present_doc_ids: list[str]) -> int: ...


@runtime_checkable
class LexicalSearchVectorStore(Protocol):
    """Optional exact-keyword retrieval capability for hybrid search."""

    async def search_text(self, query: str, limit: int = 5, workspace_id: str | None = None) -> list[RetrievedChunk]: ...
